package com.example.post_playback_rating_frontend.core

import android.util.Log

/**
 * Feature flags centralized.
 * BuildConfig.USE_MOCKS should be generated by Gradle; default true.
 */
object FeatureFlags {
    private const val TAG = "FeatureFlags"

    // PUBLIC_INTERFACE
    /** Returns whether mocks mode is enabled. */
    val useMocks: Boolean
        get() = try {
            BuildConfigHolder.useMocks()
        } catch (e: Throwable) {
            true
        }

    // PUBLIC_INTERFACE
    /**
     * Emits a one-time clear log note indicating that the application is running in MOCK MODE.
     * This is useful for QA and CI logs to confirm the current execution mode.
     */
    fun logMockModeIfEnabled() {
        if (useMocks) {
            Log.i(TAG, "==============================================")
            Log.i(TAG, "MOCK MODE ENABLED: Using in-memory/local mock data")
            Log.i(TAG, "No network initialization will be performed.")
            Log.i(TAG, "==============================================")
        }
    }
}

/**
 * Wrapper to avoid direct BuildConfig references if not generated with field.
 */
object BuildConfigHolder {
    // PUBLIC_INTERFACE
    /** Returns the BuildConfig-driven flag; true by default. */
    fun useMocks(): Boolean {
        return try {
            val clazz = Class.forName("com.example.post_playback_rating_frontend.BuildConfig")
            val field = clazz.getField("USE_MOCKS")
            field.getBoolean(null)
        } catch (_: Throwable) {
            true
        }
    }
}
