package com.example.post_playback_rating_frontend.core

/**
 * Feature flags centralized.
 * BuildConfig.USE_MOCKS should be generated by Gradle; default true.
 */
object FeatureFlags {
    val useMocks: Boolean
        get() = try {
            // PUBLIC_INTERFACE
            /** Returns whether mocks mode is enabled. */
            BuildConfigHolder.useMocks()
        } catch (e: Throwable) {
            true
        }
}

/**
 * Wrapper to avoid direct BuildConfig references if not generated with field.
 */
object BuildConfigHolder {
    // PUBLIC_INTERFACE
    /** Returns the BuildConfig-driven flag; true by default. */
    fun useMocks(): Boolean {
        return try {
            val clazz = Class.forName("com.example.post_playback_rating_frontend.BuildConfig")
            val field = clazz.getField("USE_MOCKS")
            field.getBoolean(null)
        } catch (_: Throwable) {
            true
        }
    }
}
